question_data = [
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "text": "Former United States Presidents John Adams and Thomas Jefferson died within hours of each other.",
     "answer": "True", "inanswers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "text": "In 1967, a magazine published a story about extracting hallucinogenic chemicals from bananas to raise moral texts about banning drugs.",
     "answer": "True", "inanswers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "text": "The French Kingdom helped the United States gain their independence over Great Britain during the Revolutionary War.",
     "answer": "True", "inanswers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "text": "Assyrian king Sennacherib&#039;s destruction of Babylon in 689 BCE was viewed as a triumph by other Assyrian citizens.",
     "answer": "False", "inanswers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "text": "United States President Ronald Reagan was the first president to appoint a woman to the Supreme Court. ",
     "answer": "True", "inanswers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "text": "Ottoman Empire was created in 1299.", "answer": "True",
     "inanswers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "text": "The Hundred Years&#039; War was fought for more than a hundred years.",
     "answer": "True", "inanswers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "History",
     "text": "The USS Missouri (BB-63) last served in the Korean War.",
     "answer": "False", "inanswers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "text": "The two atomic bombs dropped on Japan by the United States in August 1945 were named &#039;Little Man&#039; and &#039;Fat Boy&#039;.",
     "answer": "False", "inanswers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "text": "If you grab the bladed end of a longsword in a specific way, you will not cut yourself.",
     "answer": "True", "inanswers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "text": "Sargon II, a king of the Neo-Assyrian Empire, was a direct descendant of Sargon of Akkad.",
     "answer": "False", "inanswers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "text": "Augustus was the cousin of Julius Caesar. ", "answer": "False",
     "inanswers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "text": "In World War II, Hawker Typhoons served in the Pacific theater.",
     "answer": "False", "inanswers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "text": "Sir Issac Newton served as a Member of Parliament, but the only recorded time he spoke was to complain about a draft in the chambers.",
     "answer": "True", "inanswers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "History",
     "text": "The Battle of Trafalgar took place on October 23rd, 1805",
     "answer": "False", "inanswers": ["True"]}
]
